name: Build and Publish Docker Image

on:
  push:
     branches:
      - main
        
jobs:

  build:
    if: "!contains(github.event.head_commit.message, 'skip c')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          
      - name: Build image for client
        uses: docker/build-push-action@v2
        with:
          file: ./flask-app/Dockerfile
          context: ./flask-app
          push: true
          tags: 
            luks24/outfit-exam:latest,
            luks24/outfit-exam:${{github.sha}}
