

name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: flask-app
      PROJECT_ID: outfit7-362408
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
          credentials_json: '${{ secrets.REGISTRY_SERVICE_KEY }}'
    
    - name: Build image for client
      uses: docker/build-push-action@v2
      with:
          file: ./flask-app/Dockerfile
          context: ./flask-app
          push: true
          tags: 
            europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest,
            europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:${{github.sha}}
        
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
